[package]
name = "fourcast"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
dioxus-core = "0.6.3"
freya = "0.3.4"
ndarray = {version = "0.16.1", features = ["serde"]}
ndarray-rand = "0.15.0"
rand = "0.9.2"
serde = "1.0.219"
serde_derive = "1.0.219"
skia-safe = "0.82"